
spring.datasource.url=jdbc:h2:file:./data/consultorios-db;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

#mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=consultoriostmed@gmail.com
spring.mail.password=kajehmrpxyyavgay
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true