create table offices
(
    id                    bigint generated by default as identity primary key,
    number                int            not null,
    monthly_module_price  decimal(12, 2) not null,
    equipment             varchar(150)   not null,
    active                boolean        not null default true
);

create table tenants
(
    id                 bigint generated by default as identity primary key,
    national_id        int          not null,
    first_name         varchar(30)  not null,
    last_name          varchar(30)  not null,
    nickname           varchar(50),
    specialty          varchar(20),
    subscription_date  date,
    address            varchar(50),
    mobile_phone       varchar(30),
    email              varchar(30)  not null,
    notes              varchar(300),
    active             boolean      not null default true,
    constraint tenants_national_id_uindex unique (national_id)
);
