create table tenant_activities
(
    id           bigint generated by default as identity primary key,
    tenant_id    bigint         not null,
    office_id    bigint         not null,
    start_date   date           not null default current_date,
    end_date     date,
    monthly_rate decimal(12, 2) not null,
    notes        varchar(300),
    constraint tenant_activities_tenant_id_fk foreign key (tenant_id) references tenants (id),
    constraint tenant_activities_office_id_fk foreign key (office_id) references offices (id)
);
