create table vacancies
(
    id                 bigint generated by default as identity primary key,
    tenant_activity_id bigint      not null,
    day_of_week        varchar(10) not null,
    start_time         time        not null,
    end_time           time        not null,
    constraint vacancies_tenant_activity_id_fk foreign key (tenant_activity_id) references tenant_activities (id)
);

create table extra_hours
(
    id                 bigint generated by default as identity primary key,
    tenant_activity_id bigint         not null,
    date               date           not null,
    start_time         time           not null,
    end_time           time           not null,
    rate_charged       decimal(12, 2) not null,
    active             boolean        not null default true,
    constraint extra_hours_tenant_activity_id_fk foreign key (tenant_activity_id) references tenant_activities (id)
);
