create table payments
(
    id                  bigint generated by default as identity primary key,
    tenant_activity_id  bigint         not null,
    transaction_date    date           not null,
    type                varchar(10)    not null,
    payment_method      varchar(10)    not null default 'CASH',
    amount              decimal(12, 2) not null,
    evidence_image      blob,
    active              boolean        not null default true,
    constraint payments_tenant_activity_id_fk foreign key (tenant_activity_id) references tenant_activities (id)
);

create table expenses
(
    id           bigint generated by default as identity primary key,
    description  varchar(150)   not null,
    expense_date date           not null,
    amount       decimal(12, 2) not null,
    recurrence   varchar(10)    not null default 'NEVER',
    payment_date date,
    active       boolean        not null default true
);
